### ISSUE TITLE
BP 주간과제(4주차)

### ISSUE THREAD

**Issue by simeddk** [simeddk/HellWorld#1]
*****
### 1. 주간 목표
이번 주 본인의 주간 목표를 설정하세요.
다른 게임에서 얻은 영감을 적용해도 돼고, 현재 포트폴리오에서 목표로 삼고 있는 당면 과제를 작성해주세요.
거창한 목표보다 현실적으로 실현 가능성이 있는 목표로 설정해주세요.
`팀을 짜고 역할분담을 논의하겠다`, `날아간 프로젝트를 복구하겠다` 같은 외적 요소도 상관 없습니다.
### 2. 결과물
구현된 결과를 대표할 수 있는 스크린샷을 첨부해주세요.
스크린샷을 올리기 애매한 경우라면 아이디어 노트나 구성도로 대체해도 상관 없습니다.
영상으로 올리고 싶은 경우에는 너튜브나 기타 영상 사이트에 올린 후 링크로 걸어주세요.
```c++
ex) 1. Dissolve 구현 결과
```
![Image](https://user-images.githubusercontent.com/65766852/208929567-6db52faf-3ebc-40d4-ab4b-3d8fa085b866.png)
```c++
ex) 1. 탈 것 구현 결과
```
![Image](https://github.com/simeddk/HellWorld/assets/65766852/85db0b9d-7655-4cec-9b11-a5bbfcf182cb)

### 3. 고찰
만들면서 알게 된 사실이나 미흡했던 부분, 추후 방향성이나 계획 등등에 대해 수기 형태로 작성해주세요.
원래 하고자 했던 것들이 잘 되었는지, 안되었다면 어떤 부분이 원인인것 같은지, 해결을 위해 어떤 방식을 사용할지
문제 해결의 참고를 위해 찾아 놓은 기술문서 링크를 걸어도 됩니다.
```c++
ex)
Dissolve 효과는 만족스럽다.
그런데 머티리얼이 많은 메시를 사용하게 된다면?
액터 안의 모든 PrimitiveComponent에게 다이나믹머티리얼을 적용할 필요가 있다.
소유하고 있는 무기 액터들에도 Dissolve 효과를 적용하려면 어떻게 해야 할까?
자기 자신을 Owner로 삼고 있는 다른 무기 액터들을 배열 형태로 얻어오는 함수가 블루프린트에는 없는 것 같다.
C++에서는 Children이라는 멤버 변수가 있었는데 대체 함수가 있는지 조사해보겠다.
https://docs.unrealengine.com/4.27/en-US/API/Runtime/Engine/GameFramework/AActor/Children/
```
***
## 제출자
|이름|제출했는가?|
|:--|:--|
|`권혁준`|O|
|`김강산`||
|`김현범`|O|
|`박석규`|O|
|`송환석`|O|
|`유창훈`|O|
|`이수민`||
|`이윤기`|O|
|`전우진`|O|
|`정유경`|O|
|`한유태`|O|

**Comment by HanYooTae** [comment]
**1. 주간 목표**
- Player UI생성 및 레벨 당 스킬 해금 system 구현

- 스테이지 별 몬스터 배치

- 몬스터 공격 기능 추가

- 가능하다면 EQS도 추가



**2. 결과물**
- Stage1 Enemy 처치 후 Destroy됨과 동시에 Stage2로 넘어가는 Door Open Event 실행

-  Door 반대편의 Point Light를 Overlap한 후에 Close Door Event 실행(Do Once)

- GameMode를 통해 Stage2의 Enemy들의 Count가 0이 된다면 Stage2 Boss의 Capsule Collision 활성화 중
https://www.youtube.com/watch?v=S6Z63WsyLFg

**3. 고찰**
- Enemy 처치 시 문이 열리는 이벤트를 Enemy 또는 Door에서 처리하려고 하였으나, 관리포인트가 많아진다는 것을 간과함
-> Level BluePrint에서 Tick이벤트를 이용하여 Enemy 처치 시 Open Door Event 실행 및 Tick 종료


P.S.
집 대공사로 인해 작업량이 많지 않습니다. 다음 주까지 공사긴 한데.. 목표한 부분들 최대한 많이 구현해보겠습니다.

**Comment by hyounbum** [comment]
#1. 주간목표

* enemy 스프라인깔기

* enemy 몽타주 재생
* 
* enemy EQS구현 사운드큐 사용


#2. 결과물

* ![Image](https://github.com/simeddk/HellWorld/assets/123162344/e315bfdb-0026-4af8-bd34-7b01ffe7fca2) 자료를 찾아 적용

* BP_enemy 생성 및 이동 몽타주 재생


#3. 고찰

* 처음사용해서 적용하는 사운드큐가 문제가 많았음 에러가 너무많이떠서 영상감마저 안나옴 

* enemy를 다시 처음부터 작업할 계획

**Comment by las7460** [comment]
주간목표

다음스테이지로 가게 볼륨 제작
enemy 몽타주 제작(아직 다 미완성)

결과물

볼륨으로 가게되면 다음스테이지로 가는 영상 녹화했는데 용량으로인해
못올려서 진행한것중 간단한거 스크린샷 한장 올립니다.
![123](https://github.com/simeddk/HellWorld/assets/126652838/31a127bf-0c1a-4053-b712-79689b3304af)

3. 작업을 많이못해서 아직 진행상황이느려서
다음스테이지로 갈때 아우라같은거 붙일예정
그리고 적 애니메이션 제작중 미흡한게 많아 작업중입니다.
할작업이 많은데 새로운기술들을 써보려해서 찾아보고있는중입니다.

**Comment by namenam1** [comment]
### LeeYG
- 6/ 23 메인보드사망


![Image](https://github.com/simeddk/HellWorld/assets/136696020/53fbdc5c-94e6-4bc0-9b44-5248611365ff)



-  6/ 27 부품교체 완료 후 복구중


![Image](https://github.com/simeddk/HellWorld/assets/136696020/29bda459-c02c-42d8-85f6-42f3b265e743)

**Comment by takndr** [comment]
전우진
 
1. 주간 목표

 - 적 사망 시, Dissolve효과 발생
 
 - 공격 또는 스킬 몽타주 별로 적 Hit Reaction 다르게 설정(공중에 뜨거나, 다운되거나, 일반적으로 맞거나)


2. 결과물

  - Dissolve Test 영상 : https://www.youtube.com/watch?v=rD0dxu2NnwQ
  

3. 고찰

 - 생각보다 시간이 많이 부족해서, 다채롭게 진행하지는 못하였지만, 처음 적용한 Dissolve가 나름 신선하고 어려웠음
 - 아직 Behavior Tree에서 잔버그 등이 많음
 - 이번주에는 몽타주별 데미지 및 간단한 UI를 설정

**Comment by Songhwanseok** [comment]
##1. 주간 목표
이번 주에 집안사정이 있어서 구현할 시간이 없었습니다. 대신 구현 계획을 올리도록 하겠습니다.


##2. 결과물

![Image](https://github.com/simeddk/HellWorld/assets/50862481/f35e2392-4833-4e1f-9cae-2d8ee3339935)

적 위에 마우스를 올리면 체력바가 출력되도록 함.
왼쪽에는 임무목표를 띄우고, 아래쪽에는 현재 체력 상태와 탄약 상태를 확인가능



![Image](https://github.com/simeddk/HellWorld/assets/50862481/984a910e-d25c-4967-b7e6-0fcb051f1885)


맵 구성. 시작지점에서 출발해 방의 목표를 획득하고 모든 적을 처치해야 도착지점으로 나갈 수 있도록 함
각 방마다 적이나 상자를 배치.
상자는 열면 랜덤하게 체력 회복 또는 폭발 함정(발동하고 피할 수 있을정도로 시간을 주기로 함)이 출현

**Comment by RedHairWanderer** [comment]
1) 주간목표
잠입물에 맞게 적군들 설치 및 상호작용 만들기

2)결과물

![Image](https://github.com/simeddk/HellWorld/assets/126764868/747a48f7-a782-47d3-b784-cc83b17ee8e3)
![Image](https://github.com/simeddk/HellWorld/assets/126764868/51ef44f3-154f-4d99-b86e-0a8c27f2a51e)
![Image](https://github.com/simeddk/HellWorld/assets/126764868/1d40f8c3-c9e0-4db1-a21e-28ec462c62bc)


3)고찰

PatrolPath 에 Enemy가 반응되지 못하고 있음을 발견
Enemy를 피격 시, 플레이어에게 시선 향하기 + 멀어지면 공격자세에서 대기자세로 돌아가기 확인됨

좀 더 PatrolPath를 유동적으로 컨트롤 할 수 있게 블루프린트 수정작업하기

조명과 구조물을 더 놓아 잠입물에 맞는 분위기가 될 수 있도록 조정

-정유경

**Comment by HyukJun46** [comment]
주간 목표
1인칭 좀비게임
 - 캐릭터와 적 이벤트에서 오류를 해결하기 위해 이번 주차는 진행이 느렸습니다.

​목표

- Widget 구현 (Aim, 체력, 남은총알)

- 맵 클리어를 도와주는 도움요소 생성

- 정해진 장소로 점프하거나 행동할 수 있는 이벤트 생성

**Comment by kaikenesis** [comment]
1. 주간목표

CombatRPG만들기
- 원거리 AI 추가
- 구르기 무적추가

2. 결과물
https://youtu.be/gairNuteTCo

3. 고찰
카메라가 이상하게 움직인다거나, projectile 방향이 틀어지거나, enemy의 반응이 이상한게 상당히 많았고,
이를 해결하기 위해서
카메라는 대상이나 기준을 바꿔본다거나,
projectile은 linetrace를 통해서 충돌지점까지의 방향으로 설정해주거나 하는식의 시도를 해보았으나
만족할만한 결과가 나오지않았던게 아쉬웠음.

**Comment by hyounbum** [comment]
1. 주간목표
enemy eqs조작


2. 결과물


![Image](https://github.com/simeddk/HellWorld/assets/123162344/909c906f-ce45-4425-a937-c923e1bbdaf7)



![Image](https://github.com/simeddk/HellWorld/assets/123162344/4549f7f2-7421-418f-8bda-2be00643d05f)



![Image](https://github.com/simeddk/HellWorld/assets/123162344/5d82981e-08b0-4d02-8b84-c8f3651dbef2)

BS완성



![Image](https://github.com/simeddk/HellWorld/assets/123162344/eb8bad14-927b-47d1-99cb-46958b865ac7)

스프라인 깔기



![Image](https://github.com/simeddk/HellWorld/assets/123162344/5c6b4c11-428c-4d3c-bfcc-f1b5ced1bfa5)

블루프린트 모아둔 사진

3. 고찰
     컴퓨터 기능 문제로인해 많이 지연된 개발로 인해 목표까지 도달하지 못했습니다. 원래의 목표는 
     사운드 kit 사용이었지만  많은 오류로인해 포기하게 되었습니다.
     현제 제출하는 프로젝트도 완성본이아니며 에러 해결을 하다 더 이상 연기할 수 없어 제출합니다.
