### ISSUE TITLE
BP 주간과제(5주차)

### ISSUE THREAD

**Issue by simeddk** [simeddk/HellWorld#2]
블프 프로젝트가 마무리 되어야 할 마감주입니다.
써야할 내용은 매주 같습니다.

### 3. 고찰
***
저번 주에 과제 제출 안한
김강산, 이수민
잊지 않겠습니다.

김강산, 이수민...
김강산, 이수민...
김강산, 이수민...

![Image](https://user-images.githubusercontent.com/65766852/210189974-28f3fbac-98a4-4106-86e7-8374ee40d5a0.png)

***
## 제출자
|이름|ID|제출했는가?|
|:--|:--|:--|
|`권혁준`|`HyukJun46`|O|
|`김강산`|``||
|`김현범`|`hyounbum`||
|`박석규`|`kaikenesis`|O|
|`송환석`|`Songhwanseok`|O|
|`유창훈`|`las7460`|O|
|`이수민`|`leesumin122`|O|
|`이윤기`|`namenam1`||
|`전우진`|`takndr`|O|
|`정유경`|`RedHairWanderer`|O|
|`한유태`|`HanYooTae`|O|

**Comment by RedHairWanderer** [comment]
주간목표
미로에서 줄지어 나오는 Enemy들을 마법능력으로 파쇄해서 골인지점에 축하받기
Enemy를 격파할 때마다 획득 경험치나 게이지 표현하기
주변을 어둡게 만들어 Enemy들이 다닐 때 머리위에 조명 달아주기

결과물


![Image](https://github.com/simeddk/HellWorld/assets/126764868/a3d180ad-24b3-4e62-b29c-b901792ff1f4)
![Image](https://github.com/simeddk/HellWorld/assets/126764868/a72e5975-a4d6-4608-a927-f2877294b75d)
![Image](https://github.com/simeddk/HellWorld/assets/126764868/30145510-f495-461a-96ef-23415e343abb)



고찰
여러마리를 줄지어서 Patrol로 나오는 것에 에러발생
Enemy를 쓰러뜨려서 획득한 점수로 골인 지점에 다른 마네킹들이 춤으로 환영해주는 것을 표현하고 싶었는데 트리거 발동자체를 어떻게 설정해야할지 고민..

**Comment by kaikenesis** [comment]
1. 주간목표
마무리단계라 4주차까지에서 발견한 버그들을 해결하는 방향으로 진행
- Enemy끼리 팀킬을 못하도록 추가로 조건을 달아서 작성
- fireball과 iceball이 같은팀은 닿아도 통과되도록 작성
- fireball과 iceball이 overlap시 현재 캐릭터가 들고있는 타입의 속성으로 데미지와 디버프가 적용되는 것을 개선
(ex. fireball을 던진 후 magic을 iceball로 해두면 데미지와 디버프가 iceball로 적용되는 버그)
- hit모션이 2번 재생되거나 너무 늦게나오는것을 개선

2. 결과물
https://youtu.be/GNKVy6rEdWg

3. 고찰
5주 동안 작업을 진행한 결과 만들어진 결과물보다 더 많은 기능을 추가하고 싶었지만,
도중에 발생하는 버그에 대해 고민하고 수정하는데 시간이 생각보다 많이 들어가 추가적인 기능들을 마저 못넣은게 아쉽다.
그래도 구현하려고 했던 양에 비슷하게 결과가 나온것에 대해선 나름 만족하고있다.

**Comment by takndr** [comment]
1. 주간 목표

  - 메인 메뉴 위젯을 만들어 캐릭터 선택 시에 따라 다른 캐릭터 스폰되어 조작할 수 있도록 설정
  
  - 카메라 이동하는 효과를 주어 입체감 있게 설정
  
  - 캐릭터 선택 시, 특수한 행동을 주어 이 캐릭터를 선택했다는 것을 인지
  

2. 결과물
  https://youtu.be/YF8eTILy2AA
 
3. 고찰
  
  - 5주간 진행하면서, 수업시간 때 배운거 이외의 것을 적용 시켜보고자 하였는데, 생각보다 이해하는 데에 시간이 상당히 소요되었음

  - 기존에 생각했던 것 보다 많은 사항들을 진행하지 못하였으나, 꾸준히 진행해서 마무리 진행할 예정

  - 기존에는 Play할 수 있는 맵을 3~4개 정도로 생각하였으나 시간이 생각보다 부족하였

**Comment by HanYooTae** [comment]
1. 주간 목표

Player UI생성 및 레벨 당 스킬 해금 system 구현

스테이지 별 몬스터 배치

몬스터 공격 기능 추가

가능하다면 EQS도 추가

2. 결과물
- Stage2에서  Enemy를 처치해야 Boss Collision이 Enable -> Boss를 처치해야 Door_Open Event 실행

https://www.youtube.com/watch?v=E0X2JT9AB9g

3. 고찰
- Stage2에서는 Enemy를 처치해야 Boss의 Collision을 Enable시키려 위한 작업이 여러 변수들로 인하여 시간이 상당히 많이 들었습니다.
- 여러 변수들로 인해 Stage3, 4와 Enemy의 Attack, EQS, Player의 Widget 등을 구현하지 못한 것이 좀 아쉽네요..

**Comment by las7460** [comment]
주간목표
다음스테이지로 넘어갈때 볼륨생성중 끊기는거 보완
보스생성
적 공격기능

2. 결과물
이번주는 개인사정으로 인해 작업을 거의 하지못해서
결과물 사진을 따로 올리진 못했습니다.

3. 고찰
일단 제가 배우고 알던 기술들을 사용하는데도
생각지도 못한곳에서 변수가 생기게되며 새로운 기술들도 찾아보고 이해하려다보니 시간이 많이 지체된 것 같습니다.

그리고 보스 공격 작업 등등 여러가지를 못해서 아쉬운 것 같습니다.

**Comment by HyukJun46** [comment]
권혁준
게임 주제 : 1인칭 좀비 FPS
 - 맵 안의 좀비들을 피하고 처치하여 생존 이벤트를 활용해 클리어

1. 주간 목표
 - 비헤이비어트리를 이용하여 여러마리의 적에게 다른 이벤트를 구현하고자 하였으나 미완료

- 플레이어 무기 이벤트 에러 (장전과 발사 애니메이션을 구현하고자 하였으나 에러)
 1) 에셋의 Material이 에러로 인해 삭제되어 무기가 사라졌습니다.

 - Widget 구현 (Widget의 사용법 미숙으로 인한 미완료)

 - 맵 클리어를 도와주는 도움요소 생성 (완료)

 - 정해진 장소로 점프할 수 있는 이벤트 생성 (완료)

2. 결과물
 - 에러가 많아 플레이가 불가능합니다. 사진으로 대체 하였습니다.

![Image](https://github.com/simeddk/HellWorld/assets/126559827/d9b6789f-e0f9-472c-b888-fa936d027493)




3. 고찰
 - 캐릭터와 배경 및 애니메이션에 대한 과도한 시간 투자

 - 너무 많은 적들을 만들고자 했던 욕심

 - 플레이어에게 너무 많은 이벤트를 주고자 했던 욕심

 - 안일한 시간 분배

 - 언리얼엔진 사용법에 대한 학습 부족 (비헤이비어 트리, 이벤트 구현)

※ 추후 계속 진행하여 완성된 결과물을 만들겠습니다. ※

**Comment by Songhwanseok** [comment]
1. 주간목표
AI 구현하기
스테이지 구현하기(시간 부족으로 구현 실패)

2. 결과물
https://youtu.be/JgzfzTxRwPQ

3. 고찰
생각보다 이상한 곳에서 시간 소모가 심했음(변수 초기화가 안되는 경우로 몇 시간 씩 허비, 블랙보드에 키 안 넣고 헤메기 등)
알고 있다고 생각하던 것을 직접 구현해 보려니 모르는 부분이 생각보다 많았음(인터넷 서칭에 시간을 너무 많이 보냄)
새로운 기능을 추가할 때마다 버그가 늘어나는 것이 눈에 보여서 개발이 계획대로 되지 않는다는 것을 느꼈음
완성 못한 것이 아쉬워서 나중에라도 구현해 볼 예정입니다.

**Comment by leesumin122** [comment]
저번주에 까먹고 까먹고 하다가 타이밍을 놓쳐서 이번주에 몰아내자는 생각으로 제출을 미뤘습니다 죄송합니다 ㅜ

1. 주간목표
   보스 캐릭터를 만들고 클리어 위젯까지 띄우는 것이 목표였으나 위젯은 시간 부족으로 실패
   잡몹이 플레이어와 일정 거리에 도달하면 풀숲에서 다가오도록 설정
   물에 빠지면 사망(랙돌)
2. 결과물


![Image](https://github.com/simeddk/HellWorld/assets/136589875/da723691-d7a7-4391-af92-eaf794fa9d4d)
![Image](https://github.com/simeddk/HellWorld/assets/136589875/d7929c67-de19-4637-bbac-a4922f7f86d3)
![Image](https://github.com/simeddk/HellWorld/assets/136589875/0190f992-6802-4662-8ef6-69232c7b57b3)
![Image](https://github.com/simeddk/HellWorld/assets/136589875/9f7d4791-9919-4827-b181-66cd15ff247e)
![Image](https://github.com/simeddk/HellWorld/assets/136589875/1f86ef3c-e9da-46a8-8e0f-58d24a2c32c2)

3. 고찰
   랙돌시 캐릭터의 형태가 이상하게 늘어났고, 맵이나 플레이어 메시, 스켈레탈이 용량을 너무 큰걸 사용해서 후회스러움.
   구상을 너무 크게 하다가 시간에 쫓기다보니 버그도 많아지고 수정하는데 시간이 소요되어 원하는 매주마다 결과를 내지 못했 
   던 것 같음. 수업때 따라서 하는 것과 혼자서 프로젝트를 만든다는 것은 많이 다르다는 것을 느꼈고, 좋은 경험이라는 생각이 들 
   었음. 시간이 남는다면 블루프린트 포트폴리오도 천천히 완성도를 높여갈 생각입니다.
