### ISSUE TITLE
C++ 주간과제(3, 4주차)

### ISSUE THREAD

**Issue by simeddk** [simeddk/HellWorld#5]
### 작성한 프로젝트는 반드시 github 리포지토리에 업로드 할 것
***
### 3. 고찰 및 다음주 할 것
***
## 제출자
|이름|ID|제출했는가?|
|:--|:--|:--|
|`권혁준`|`HyukJun46`|O|
|`김강산`|`kks1105`|O|
|`김현범`|`hyounbum`|O|
|`박석규`|`kaikenesis`|O|
|`송환석`|`Songhwanseok`|O|
|`유창훈`|`las7460`|O|
|`이수민`|`leesumin122`||
|`이윤기`|`namenam1`||
|`전우진`|`takndr`|O|
|`정유경`|`RedHairWanderer`|O|
|`한유태`|`HanYooTae`|O|

**Comment by HanYooTae** [comment]
1. 이번주에 한 것
https://www.youtube.com/watch?v=oI6YeIkRpdE

2. 스크린샷


![Image](https://github.com/simeddk/HellWorld/assets/41534351/0d48695d-2815-42a2-bb6c-c3d474bd1cb8)




![Image](https://github.com/simeddk/HellWorld/assets/41534351/74e04a5e-b5be-4239-908f-41c86288facd)



3. 고찰 및 다음주 할 것
- (유태) 캐릭터 배속 구현 및 스킬트리 구현
- (현범) 인벤토리 구현

**Comment by RedHairWanderer** [comment]
1. 이번주에 한 것

- 캐주얼 장르에 맞는 에셋 찾기 2..
- BP_Player 틀 잡기 + 청소에 맞는 충돌체 개념(설정)잡기
- 충돌체 개념에 대해 전 수업에서 배운 것들 복습 + 유투브에서 언리얼 엔진을 활용한 다양한 방법 알아내기

2. 고찰 및 다음 주 할 것

- BP_Player 충돌이 많이 나와서 버그수정 및 보완 중..
- 계속해서 언리얼엔진으로 활용할 수 있는 다양한 방법 알아내기
- 전체적인 게임 틀을 잡아내는 기획서 쓰기

**Comment by las7460** [comment]
이번주에 한것

- 기본 키보드 이동 말고 마우스로 클릭하면 해당 위치로 가게끔 작업

- 장애물도 회피하게끔 작업

- 유튜브, 구글로 새로운 기술들 알아보기

고찰 및 다음주 할것

- 해당 새로운 작업중 빌드오류로 문제 찾아내는중
- 이번주에 작업량이 적었는데도 시간을 꽤 많이 쓴거같음
- bp_player 애니메이션 및 공격 스킬 작업

**Comment by HyukJun46** [comment]
이번주에 한것
 - 기존의 캐릭터 FPS이벤트를 수업 복습 후 수정
 - C++의 여러 함수들 학습
 - 적 애니메이션 적용(이벤트 미구현)
 - Epic Games 안의 샘플예제들을 보며 구현방법 생각

고찰 및 다음주 할 것
 - 어려운 이벤트들은 C++과 블루프린트를 병행하며 작업
 - 캐릭터 이벤트 구현
 - 적 이벤트 구현
 - 맵 이벤트 구현

**Comment by kks1105** [comment]
1. 이번주에 한 것
위젯조정 플레이어캐릭터 이동블렌드스페이스 8축으로변경 무기처럼보이는 스켈레탈메쉬 장착 캐릭터에맞게애니메이션수정 공격 기능 껍대기    
2. 스크린샷


![Image](https://github.com/simeddk/HellWorld/assets/93188124/e7a6a2ef-fa6c-428c-b646-80fcf6c927e0)


3. 고찰 및 다음주 할 것
무슨이유인지 8방향중 앞뒤로움직일때만 캐릭터가덜덜떨리는현상이있음 에임밀리는현상 과 소켓에안껴지고 자꾸튕기는현상 앵커조정과 스태틱매쉬 스켈레탈메쉬로변경하여해결 다음주:에너미캐릭터만들기

**Comment by kaikenesis** [comment]
1. 이번주에 한것
마우스 위치에 따라 BuildingObject를 Spawn시키고 이미 스폰되어있는 오브젝트에 부딪치면 해당 오브젝트에 미리 정해둔 소켓위치에 맞게 스폰위치가 정해지도록 작성

2.
https://youtu.be/-mmA-JZySXk

3. 고찰 및 다음주에 할것
이미 스폰되어있는 오브젝트와, 캐릭터와 겹칠시 스폰이 되지않도록 함.
이를 육안으로 확인가능하도록 머티리얼을 변경할 예정.

**Comment by Songhwanseok** [comment]
1. 이번주에 한 것
캐릭터 구현(기본 이동, 점프 등)
간단한 맵 생성

2. 스크린샷


![Image](https://github.com/simeddk/HellWorld/assets/50862481/60ea5452-26a9-4180-adb2-3c512c910e1d)

3.고찰 및 다음주 할 것

인벤토리 구현, 상점 구현

**Comment by takndr** [comment]
# 2,3주차 미니맵 및 캐릭터 무기 작업

## 작업 내용
+ 좌측 하단에 간단하게 현재 맵을 볼 수 있는 미니맵 제작
+ 캐릭터 Skeletal Mesh 설정
+ 사용할 장비(칼3개, 활3개)부분 필드 드랍 블루프린트 생성 및 미니맵 스프라이트 지정


## 작업 결과(Youtube 링크)
https://youtu.be/KEj83_MtWug

## 후기
+ 미니맵 제작 시, 플레이어 및 적, 드랍 장비들을 표시하는 방법에 대해 여러가지 방법을 찾아보았는데, Sprite관련 컴포넌트 사용시 되게 깔끔하게 진행되어 해당 내용으로 채택
+ 구한 에셋들을 최대한 활용하여 제작
+ 컴포넌트를 추가하여 블루프린트를 만들었을 때, 디테일 패널에 하나도 보이지 않는 현상때문에 골머리를 앓고 있었는데 이것저것 다해보았다가 블루프린트를 다시 작성하는걸로 진행
+ 인벤토리 위젯 완성하는 중에, 가방쪽 패널에는 버튼이 들어갔음에도 버튼이 활성화되지 않는 현상이 있어서 완성시키지 못하였음...
+ 그리고 빌드 할때 아이템슬롯 관련 위젯에서 에셋이 없다고 에디터가 터지는 현상이 있었는데, 아무리봐도 문제가 없어보여서 에러창 종료하고 에디터 재시작하니 무난하게 재시작 되었음...

## 이후 작업내용
+ 캐릭터가 직접적으로 착용할 무기 제작 및 인벤토리의 장비창과 연계하여 인벤토리창 우클릭하여 장비가 착용될 수 있게 진행
+ 칼의 공격 몽타주 및 활의 공격 몽타주 진행
