### ISSUE TITLE
C++ 주간과제(7, 8주차)

### ISSUE THREAD

**Issue by simeddk** [simeddk/HellWorld#8]
### 작성한 프로젝트는 반드시 github 리포지토리에 업로드 할 것
***

![Image](https://github.com/simeddk/HellWorld/assets/65766852/e41ff0c8-a1a0-40c3-a3c4-8f4aa102595d)

### 3. 고찰 및 다음주 할 것
***
## 제출자
|이름|ID|제출했는가?|
|:--|:--|:--|
|`권혁준`|`HyukJun46`|O|
|`김강산`|`kks1105`|V|
|`김현범`|`hyounbum`|O|
|`박석규`|`kaikenesis`|V|
|`송환석`|`Songhwanseok`|V|
|`유창훈`|`las7460`|V|
|`이수민`|`leesumin122`||
|`이윤기`|`namenam1`||
|`전우진`|`takndr`|O|
|`정유경`|`RedHairWanderer`|V|
|`한유태`|`HanYooTae`|O|

**Comment by kaikenesis** [comment]
1. 이번주에 한것
저번주 계속하고있던 Widget 작업과 전체적인 코딩의 잘못된 구조를 개선하는 작업

현재 만들고 있는 위젯을 화면에 띄우기 위해 입력을 PlayerController에서 바인드된 키를 입력받아 Component에 함수를 실행시켜 viewport에 추가해주면서 Interface를 통해서 Widget에 세팅을 해주는 작업을 하고있고

2.

3. 다음주에 할것
우선 하고있는 작업을 어느정도 완성시키고 화면에 띄우는 것이 목표

**Comment by HanYooTae** [comment]
**1. 이번주에 한 것**
- TimeDilationComponent : GlobalTimeDilation -> CustomTimeDilation으로 변경
- OSS Create/Destroy Session 구현
- 인벤토리 전면 수정

1. 상호작용 가능한 오브젝트
-> 상호작용을 위한 InteractComponent 생성
InteractComponent를 가진 오브젝트가 무엇인지 그리고 player, Item과의 상호작용 상태를 확인하기위한 Component
-> PlayerCameraLineTrace
PlayerCamera의 시작되는 LineTrace로 InteractComponent를 가진 오브젝트를 찾는다.
-> Interact할 물체 정보창Widget 생성
LineTrace에서 찾은 오브젝트가 InteractComponent를 가졌다면 해당 오브젝트의 정보창, 기능, 갯수 등을 표기한 정보창 spawn

2. InventoryComponent 생성
-> Item, FoodItem(Item을 상속받은) C++ 클래스 생성
  게임중 이름, 설명, 무게, 중복소유가능여부, 총 소유갯수 포함
-> Interact하여 Item일경우 Data를 가져와 InventoryWidget으로 data를 전달(미구현)


**2. 스크린샷**

![Image](https://github.com/simeddk/HellWorld/assets/41534351/fd1fb4b9-9984-487a-b539-305043c87d36)


<인벤토리 UI 수정>



![Image](https://github.com/simeddk/HellWorld/assets/41534351/2cbf93e9-5151-4dc7-873c-4ffbc79f8517)


<Object와 Interact>


**3. 고찰 및 다음주 할 것**
- OSS 마무리
- Item Mesh 및 Inventory Thumbnail 추가

**Comment by takndr** [comment]
# 6주차 Weapon Component 변경 및 화살 작

## 작업 내용
+ 이전에 만들었던 장비를 관리하는 Weapon Component 작업
+ 활 장착 완료시 화살이 자동적으로 활시위에 장착

## 후기
+ 기존에 만들었었던 것들을 재조정하는 것이 처음이라 생각보다 구조 잡는 것에 애먹었었음
    
+ 활 공격 진행 시, 화살의 위치가 조금씩 바뀌는 것이 확인
   
## 이후 작업내용
+ 비무장 시, space로 점프 / 무장 시에는 회피 기동 진행
+ 칼 공격 시, 콤보 공격 이어지도록 설정
+ 활 공격 시, 화살이 발사 되고, 화살은 히트스캔이 아닌 투척형태로 진행
  + 궤도를 설정 할 수 있으면 설정
+ 화살 관련 노티파이 설


# 7주차 칼 콤보 공격 및 화살 공격, 보스 간단 작업

## 작업 내용
+ 칼 공격 시, 콤보 공격 이어지도록 진행 
+ 활 공격 시, 화살이 발사 되도록 진행
+ 보스 및 보스 애니메이션 설정 간단 세팅 작업 진행

## 후기
+ 칼 콤보 공격 진행 시, 아직 매끄럽지 못한 부분이 존재
+ 활 공격 진행 시, 화살이 발사 되는 것을 확인하였으나, World space?가 아닌 local space로 이동 -> 보스 작업 얼추 진행 이후 피격 테스트 진행할 때 맞춰 변경 작업 진행 예정
   
## 이후 작업내용
+ 비무장 시, space로 점프 / 무장 시에는 회피 기동 진행
+ 체력 별로 나누거나 체력 전체를 까면 페이즈가 변경하거나 하는 형태로 진행
   + 1페이즈 - 물리 공격(입공격, 앞발공격)
   + 2페이즈 - 비행하면서 화염 브레스
   + 3페이즈 - 다시 땅에 내려와서 물리 공격 및 지상 브레스
+ 보스 전용 Hp위젯 제작

**Comment by RedHairWanderer** [comment]
1. 이번주에 한 것
- 오류가 걷잡을 수 없이 많아져서 엎고 다시 기틀부터..
- 타 언리얼 엔진으로 비슷한 장르와 만들고 싶은 느낌과 비슷한 자료들을 빗대어 흉내내보기
- 문제가 많아진 이유에 대한 원인 찾기, 문제해결방도 잡기


2. 고찰 및 다음주 할 것
- 흉내내본 다른 작품 스크린샷 제출
- 최소한의 버그 발생을 위해 계속해서 보완

**Comment by las7460** [comment]
1. 이번주에 한것

작업중 원하는 방향에 맞지않고 오류가 많어서
현재 작업중이던 액션관련 게임을 갈아엎음

유튜브로 여러가지 게임 찾아봄

2. 다음주 할것

새로운 작업에 맞는 기술 찾아보기

bp_player 기본셋팅 및 애니메이션 적용

**Comment by kks1105** [comment]
1. 이번주에 한 것
현재수업중에하는것처럼 코드변경중 플레이어클래스에 몰아놨던 기능 배치중

3. 다음주 할 것
현재 변경중인거 정리끝내고 안터지게하기

**Comment by Songhwanseok** [comment]
1. 이번주에 한 것
원활한 빌드를 위한 컴퓨터 부품 교체 및 운영체제와 개발 프로그램 세팅

2. 고찰 및 다음주 할 것
저번 주에 하려고 했었던 플레이어 작업 마무리

**Comment by HyukJun46** [comment]
1. 이번주에 한 것
 - C++ 강의 복습
 - 각 이벤트를 프로젝트별로 나누기
 - 캐릭터 이동 프로젝트 완료
 - 캐릭터 무기(맨손) 프로젝트 완료

2. 고찰
 - 어떻게 프로젝트를 나눌것인지에 대한 고민을 너무 오래함.
 - C++ 및 언리얼 사용법 미숙

3. 다음주 할 것
 - 한손, 양손, 총 등 프로젝트로 나누어서 작업할 예정
 - C++ 강의 복습
